namespace Opc.Client.Core.Domain.ValueObjects;

/// <summary>
/// Represents a snapshot of an OPC tag's data, including its value, quality, and the time of measurement.
/// </summary>
/// <remarks>
/// Implemented as an immutable record, this value object ensures that a tag reading is treated as a single, consistent unit.
/// </remarks>
/// <param name="Value">The data value read from the OPC tag.</param>
/// <param name="Quality">The quality status of the value.</param>
/// <param name="Timestamp">The timestamp of when the value was generated by the source.</param>
public record TagValue(object? Value, OpcQuality Quality, DateTimeOffset Timestamp);

/// <summary>
/// Defines the quality of an OPC tag value.
/// </summary>
/// <remarks>
/// This is a simplified representation of the OPC status code.
/// </remarks>
public enum OpcQuality
{
    /// <summary>
    /// The value is good.
    /// </summary>
    Good,
    /// <summary>
    /// The value is uncertain.
    /// </summary>
    Uncertain,
    /// <summary>
    /// The value is bad, and any associated value is unusable.
    /// </summary>
    Bad
}